fields:
  password:
    pattern: /^.{1,16}$/

  email:
    pattern: /^[A-Za-z0-9]+([\-_\.][A-Za-z0-9]+)*@([A-Za-z0-9]([A-Za-z0-9\-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,6}$/

  userName:
    pattern: /(^[^0-9])([\w a-z A-Z 0-9 @#]{2,20})$/
